'use strict';
(() => {
const D=window.STACK_DATA, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wa=(text,number=D.club.whatsapp)=>'https://wa.me/'+number+'?text='+encodeURIComponent(text);
const zone=id=>D.zones.find(z=>z.id===id);
const specs=z=>({...D.common,...z});
const priceHTML=(z,i)=>`${z.old[i]?`<del>${money(z.old[i])}</del>`:''}<strong>${money(z.prices[i])}</strong>`;
function localParts(date=new Date()) {const p=new Intl.DateTimeFormat('en-CA',{timeZone:D.club.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(p.filter(v=>v.type!=='literal').map(v=>[v.type,v.value]));}
function localDate(date=new Date()){const p=localParts(date);return `${p.year}-${p.month}-${p.day}`;}
function epoch(date,time){const [y,m,d]=date.split('-').map(Number),[h,min]=time.split(':').map(Number);const target=Date.UTC(y,m-1,d,h,min);let guess=target;for(let i=0;i<3;i++){const p=localParts(new Date(guess));guess+=target-Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);}return guess;}
const formatDate=d=>d?d.split('-').reverse().join('.'):'Выберите дату';
function session(zid,tid,date,time,count,now=Date.now()){
 const z=zone(zid),i=D.tariffs.findIndex(t=>t.id===tid),t=i>=0?D.tariffs[i]:D.specials.find(t=>t.id===tid);
 if(!z||!t)return {error:'Выберите зону и тариф.'};
 if(i<0&&zid!=='standart')return {error:'Специальные пакеты доступны в заявке только для STANDART.'};
 if(!Number.isInteger(count)||count<1||count>D.club.pcs)return {error:`Укажите целое количество компьютеров от 1 до ${D.club.pcs}.`};
 const total=(i>=0?z.prices[i]:t.price)*count;
 const startTime=t.start||time;
 if(!date||!startTime)return {total,t,startTime,error:'Выберите дату и время начала.'};
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(startTime))return {error:'Проверьте дату и время.'};
 const start=epoch(date,startTime),end=start+t.duration*3600000;
 if(!Number.isFinite(start)||localDate(new Date(start))!==date)return {error:'Укажите корректную дату.'};
 const e=localParts(new Date(end)),endDate=localDate(new Date(end)),endTime=e.hour+':'+e.minute;
 const base={total,t,start,startTime,end,endDate,endTime};
 if(start<=now)return {...base,error:'Это время уже прошло в Семее. Выберите будущие дату и время.'};
 if(i<0&&(startTime<'08:00'||startTime>'16:00'))return {...base,error:'Для 3-часового спецпакета выберите начало с 08:00 до 16:00, чтобы закончить до 19:00. Покупку и условия подтвердит администратор.'};
 return base;
}
window.STACK_TEST={session,epoch,localDate,localParts};
$('#zone-cards').innerHTML=D.zones.map((z,i)=>`<article class="zone-card"><div class="zone-visual" aria-hidden="true"><span class="hz">${z.hz}<small>Гц</small></span><span class="screen-label">${z.screen}</span></div><div class="zone-body"><span class="zone-number">0${i+1}</span><h3>${z.name}</h3><p class="zone-tag">${z.tag}</p><div class="mini-specs">${D.common.cpu}<br>${D.common.gpu}<br>${D.common.ram}</div><div class="zone-price"><strong>${money(z.prices[0])}</strong><span>/ час по прайсу</span></div><div class="zone-actions"><button class="btn secondary" data-detail="${z.id}">Подробнее</button><button class="btn" data-book="${z.id}">Выбрать и забронировать</button></div></div></article>`).join('');
$('#price-note').textContent=D.priceNote;
$('#price-tabs').innerHTML=D.zones.map((z,i)=>`<button class="tab" id="tab-${z.id}" role="tab" aria-selected="${i===0}" aria-controls="price-panel" tabindex="${i===0?0:-1}" data-zone="${z.id}">${z.name}</button>`).join('');
function renderPrices(id){const z=zone(id);$$('.tab').forEach(b=>{const active=b.dataset.zone===id;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;});$('#price-panel').setAttribute('aria-labelledby','tab-'+id);$('#price-cards').innerHTML=D.tariffs.map((t,i)=>`<button class="price-card" data-book="${id}" data-tariff="${t.id}" aria-label="${z.name}, ${t.name}, ${money(z.prices[i])}, выбрать"><h3>${t.name}</h3><p>${t.note}</p><div class="price-amount">${priceHTML(z,i)}</div><span class="choose-hint">Выбрать пакет +</span></button>`).join('');}
renderPrices('standart');$('#price-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-zone]');if(b)renderPrices(b.dataset.zone);});
$('#price-tabs').addEventListener('keydown',e=>{const tabs=$$('.tab'),i=tabs.indexOf(document.activeElement);let n;if(e.key==='ArrowRight')n=(i+1)%3;if(e.key==='ArrowLeft')n=(i+2)%3;if(e.key==='Home')n=0;if(e.key==='End')n=2;if(n!==undefined){e.preventDefault();renderPrices(tabs[n].dataset.zone);tabs[n].focus();}});
$('#specials').innerHTML=D.specials.map(t=>`<article class="special-card"><div><span class="chip">STANDART / 3 ЧАСА</span><h3>${t.name}</h3><p>Покупка 08:00–16:00<br>Игра до 19:00</p><div class="price-amount">${t.old?`<del>${money(t.old)}</del>`:''}<strong>${money(t.price)}</strong></div></div><button class="btn secondary" data-book="standart" data-tariff="${t.id}">Выбрать</button></article>`).join('');
$('#special-note').textContent=D.specialNote;$('#bonus-note').textContent=D.bonusNote;$('#bonus-link').href=wa('Здравствуйте! Расскажите, пожалуйста, об условиях бонусной программы STACK: как начисляются и используются бонусы?');
$('#bonus-rows').innerHTML='<div class="bonus-caption"><span>СУММА ПО ПРАЙСУ</span><span>БОНУСЫ ПО ПРАЙСУ</span></div>'+D.bonuses.map(v=>`<div><strong>${money(v[0])}</strong><span>→</span><strong>${money(v[1])}</strong></div>`).join('');
$('#kaspi-title').textContent=D.kaspi.title;$('#kaspi-note').textContent=D.kaspi.note;$('#kaspi-items').innerHTML=D.kaspi.items.map(v=>`<span>${v}</span>`).join('');
$('#games').innerHTML=D.games.map(g=>`<article class="game"><span class="game-mark" aria-hidden="true">${g[0]}</span><h3>${g[1]}</h3><p>${g[2]}</p></article>`).join('');
$('#why').innerHTML=[`${D.club.pcs} игровой ПК`,'Три зоны на выбор','RTX 5060 во всех перечисленных конфигурациях','Мониторы до 420 Гц','Заявка для компании','Круглосуточная работа'].map((t,i)=>`<div><span>0${i+1} /</span>${t}</div>`).join('');
const address=D.club.city+', '+D.club.address;
$('#contact-address').textContent='STACK — компьютерный клуб. '+address+'.';$('#landmark').textContent=D.club.landmark+'.';$('#contact-hours').textContent=D.club.hours;$('#phone-link').textContent=D.club.phone;$('#phone-link').href='tel:+'+D.club.whatsapp;
$('#contact-actions').innerHTML=`<a class="btn" href="tel:+${D.club.whatsapp}">Позвонить</a><a class="btn secondary" href="${wa('Здравствуйте! Хочу узнать о клубе STACK.')}" target="_blank" rel="noopener">Написать в WhatsApp</a>`;
$('#insta-link').href=D.club.instagram;$('#insta-link').title=D.club.instagramName;
$('#map-link').href='https://2gis.kz/semey/search/'+encodeURIComponent('STACK '+address);$('#floating-wa').href=wa('Здравствуйте! Хочу узнать о бронировании в STACK.');
$('#job-content').innerHTML=`<h3>${D.job.title}</h3><p>${D.job.requirements}</p><ul>${D.job.duties.map(t=>`<li>${t}</li>`).join('')}</ul><a class="btn secondary" href="${wa('Здравствуйте! Интересует вакансия администратора-кассира в STACK. Она ещё актуальна?',D.job.whatsapp)}" target="_blank" rel="noopener">Вакансия · ${D.job.phone}</a><p class="fine">${D.job.note}</p>`;
$('#faq').innerHTML=D.faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('');
$('#faq').addEventListener('toggle',e=>{if(e.target.open)$('#faq').querySelectorAll('details').forEach(d=>{if(d!==e.target)d.open=false;});},true);
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
$('#copy-address').addEventListener('click',async()=>{let copied=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(address);copied=true;}}catch{}if(!copied){const temp=document.createElement('textarea');temp.value=address;temp.style.position='fixed';temp.style.opacity='0';document.body.append(temp);temp.select();try{copied=document.execCommand('copy');}catch{}temp.remove();$('#copy-address').focus();}toast(copied?'Адрес скопирован':'Не удалось скопировать. Адрес: '+address);});
const menu=$('.menu-toggle');function closeMenu(){menu.setAttribute('aria-expanded','false');$('#navigation').classList.remove('open');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));$('#navigation').classList.toggle('open',open);});$('#navigation').addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});
document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const d=document.querySelector('dialog[open]');if(!d)return;const items=[...d.querySelectorAll('button,a[href],input,select,textarea,[tabindex]')].filter(el=>!el.disabled&&el.tabIndex>=0&&el.getClientRects().length);if(!items.length){e.preventDefault();return;}const first=items[0],last=items[items.length-1],active=document.activeElement;if(e.shiftKey&&(active===first||!items.includes(active))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(active===last||!items.includes(active))){e.preventDefault();first.focus();}});
let returnFocus=null;
function showDialog(d,trigger){closeMenu();const existing=$('dialog[open]');if(existing){existing.close();}returnFocus=trigger||document.activeElement;document.body.classList.add('locked');d.showModal();d.querySelector('h2').focus();}
$$('dialog').forEach(d=>{d.querySelector('[data-close]').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{if(!$('dialog[open]')){document.body.classList.remove('locked');if(returnFocus?.isConnected)returnFocus.focus();}});});
function details(id,trigger){const z=zone(id);$('#info-title').textContent=z.name;$('#info-body').innerHTML=`<p class="muted">${z.tag}</p><dl class="spec-list">${Object.entries(D.specLabels).map(([key,label])=>`<div><dt>${label}</dt><dd>${specs(z)[key]}</dd></div>`).join('')}</dl><h3>Тарифы зоны</h3><div class="modal-prices">${D.tariffs.map((t,i)=>`<button data-book="${id}" data-tariff="${t.id}">${t.name} · ${t.note}<span>${priceHTML(z,i)}</span></button>`).join('')}</div><p class="fine">${D.priceNote}</p><button class="btn" data-book="${id}">Выбрать и забронировать</button>`;showDialog($('#info-dialog'),trigger);}
$('#compare').addEventListener('click',e=>{$('#info-title').textContent='Сравни свой STACK';$('#info-body').innerHTML=`<p class="fine">На узком экране таблицу можно прокручивать вбок.</p><div class="compare-scroll" tabindex="0" role="region" aria-label="Сравнение зон"><table><thead><tr><th scope="col">Характеристика</th>${D.zones.map(z=>`<th scope="col">${z.name}</th>`).join('')}</tr></thead><tbody>${Object.entries(D.specLabels).map(([key,label])=>`<tr><th scope="row">${label}</th>${D.zones.map(z=>`<td>${specs(z)[key]}</td>`).join('')}</tr>`).join('')}<tr><th scope="row">1 час по прайсу</th>${D.zones.map(z=>`<td>${money(z.prices[0])}</td>`).join('')}</tr></tbody></table></div><p class="fine">${D.priceNote}</p>`;showDialog($('#info-dialog'),e.currentTarget);});
const form=$('#booking-form'),f=form.elements;
f.zone.innerHTML=D.zones.map(z=>`<option value="${z.id}">${z.name}</option>`).join('');
function tariffOptions(selected='hour'){f.tariff.innerHTML=[...D.tariffs,...(f.zone.value==='standart'?D.specials:[])].map(t=>`<option value="${t.id}">${t.name}${t.start?' · '+t.note:''}</option>`).join('');f.tariff.value=[...f.tariff.options].some(o=>o.value===selected)?selected:'hour';}
function scheduling(){const t=D.tariffs.find(t=>t.id===f.tariff.value);f.time.disabled=!!t?.start;if(t?.start)f.time.value=t.start;$('#schedule-note').textContent=t?.start?`Фиксированный пакет: ${t.note}. Время начала закреплено; произвольный перенос часов не предусмотрен.`:D.specials.some(t=>t.id===f.tariff.value)?D.specialNote:'В пакетах «2 + 1» и «3 + 2» учтено 3 и 5 часов соответственно.';summary();}
function current(){return session(f.zone.value,f.tariff.value,f.date.value,f.time.value,Number(f.count.value));}
function summary(){const r=current();const z=zone(f.zone.value);$('#booking-summary').innerHTML=`<p><strong>${esc(z.name)} · ${esc(r.t?.name||f.tariff.selectedOptions[0]?.text||'')}</strong></p><p>${formatDate(f.date.value)} · ${esc(r.startTime||f.time.value||'Выберите время')} · ${esc(f.count.value||'—')} ПК</p>${r.endDate?`<p>Окончание: ${formatDate(r.endDate)} в ${r.endTime}${r.endDate!==f.date.value?' · следующий день':''}</p>`:''}<p class="total">${r.total?money(r.total):'Стоимость уточнит администратор'}</p><p class="fine">Ориентировочная стоимость за все выбранные компьютеры. Без суммирования бонусов и дополнительных скидок.</p>${r.error?`<p class="fine">${esc(r.error)}</p>`:''}`;return r;}
function openBooking(zid,tid,trigger){f.zone.value=zone(zid)?zid:'standart';tariffOptions(tid||'hour');f.date.min=localDate();if(!f.date.value||f.date.value<f.date.min)f.date.value=f.date.min;$('#form-error').textContent='';$('#wa-result').textContent='';scheduling();const oldFocus=$('#info-dialog').open?returnFocus:trigger;showDialog($('#booking-dialog'),oldFocus);}
f.zone.addEventListener('change',()=>{tariffOptions(f.tariff.value);scheduling();});f.tariff.addEventListener('change',scheduling);form.addEventListener('input',()=>{f.date.min=localDate();$('#form-error').textContent='';$('#wa-result').textContent='';summary();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-book]'),d=e.target.closest('[data-detail]');if(b)openBooking(b.dataset.book,b.dataset.tariff,b);if(d)details(d.dataset.detail,d);});
form.addEventListener('submit',e=>{e.preventDefault();let error='',bad=null;const fail=(msg,field)=>{if(!error){error=msg;bad=field;}};if(!f.name.value.trim())fail('Укажите ваше имя.',f.name);const digits=f.phone.value.replace(/\D/g,'');if(digits.length<10||digits.length>15||!/^[+\d\s()\-]+$/.test(f.phone.value))fail('Укажите корректный номер телефона: от 10 до 15 цифр.',f.phone);if(!f.date.value)fail('Выберите дату.',f.date);if(!f.time.value)fail('Выберите время.',f.time);if(!f.count.checkValidity())fail('Укажите целое количество компьютеров от 1 до '+D.club.pcs+'.',f.count);const r=summary();if(r.error)fail(r.error,f.time.disabled?f.date:f.time);if(!f.consent.checked)fail('Для передачи заявки необходимо ваше согласие.',f.consent);if(error){$('#form-error').textContent=error;bad?.focus();return;}
const text=`Здравствуйте! Хочу забронировать места в STACK.\nИмя: ${f.name.value.trim()}\nТелефон: ${f.phone.value.trim()}\nЗона: ${zone(f.zone.value).name}\nДата: ${formatDate(f.date.value)}\nВремя: ${r.startTime} (Семей, Asia/Almaty)\nОкончание: ${formatDate(r.endDate)} в ${r.endTime}\nТариф: ${r.t.name}\nКоличество компьютеров: ${f.count.value}\nПредварительная стоимость: ${money(r.total)} за все ПК (ориентировочно)\nКомментарий: ${f.comment.value.trim()||'Нет'}${D.specials.some(t=>t.id===f.tariff.value)?'\nПрошу уточнить условия покупки специального пакета.':''}\nПожалуйста, подтвердите наличие мест и итоговую стоимость.`;
const url=wa(text);const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.textContent='Открыть подготовленное сообщение ещё раз';link.className='text-button';link.click();$('#form-error').textContent='';$('#wa-result').textContent='Отправьте сообщение в WhatsApp и дождитесь ответа администратора. ';$('#wa-result').append(link);
});
})();
